### PR TITLE
Add support for 1Password CLI app integration

### PR DESCRIPTION
**Pull request by thedavecarroll**
First, I'm not sure if I'm creating the pull request correctly. Feel free to close it if not and provide some guidelines.

I've only done minimal testing within my PowerShell module, but I think the revisions should not require any existing code changes for any consumers.

Here is my [OPassCliPS](https://github.com/thedavecarroll/OPassCliPS/tree/initial_development) repo if you wanted to check it out.

```powershell
Connect-OPAccount -Verbose
Get-OPSession | Format-List
```
```text
VERBOSE: Attempting to discover the path to 1Password CLI.
VERBOSE: Setting 1Password CLI Path session variable.
VERBOSE: Creating 1Password session with app integration.
VERBOSE: 1Password CLI Version: 2.12.0
VERBOSE: Signing into 1Password.
VERBOSE: Retrieving connected account.
VERBOSE: Creating module cache for vaults, items, and accounts.
VERBOSE: Cache creation time: 00:03:876

CliPath              : C:\Program Files\1Password CLI\op.exe
IsAppIntegrated      : True
IsAuthenticated      : True
AuthenticatedAccount : <my account>
```

```powershell
Connect-OPAccount -Domain $Domain -Email $Email -SecretKey $SecretKey -Password $Password -Verbose
Get-OPSession | Format-List
```
```text
VERBOSE: Attempting to discover the path to 1Password CLI.
VERBOSE: Setting 1Password CLI Path session variable.
VERBOSE: Creating 1Password session without app integration.
VERBOSE: Adding account for <email address>.
VERBOSE: 1Password CLI Version: 2.12.0
VERBOSE: Signing into 1Password.
VERBOSE: Retrieving connected account.
VERBOSE: Creating module cache for vaults, items, and accounts.
VERBOSE: Cache creation time: 00:01:964


CliPath              : C:\Program Files\1Password CLI\op.exe
IsAppIntegrated      : False
IsAuthenticated      : True
AuthenticatedAccount : <my account>
```

### CODE REVIEW

**Comment by jscarle** [comment]
I'll review the code when I have a free moment. There's a few things to address. First, the tests fail. Also, according to [the documentation](https://developer.1password.com/docs/cli/about-biometric-unlock), I'm not sure that --force is required. Though I understand it could be useful to have in certain scenarios.

**Comment by thedavecarroll** [comment]
Definitely no rush and no pressure.

I agree on the `--force` for `SignIn()` and I don't recall why I thought I needed it.

If the tests are trying to run against the new `SignIn()`, I'm not sure how that can be accomplished.

Not that it really matters, but I just ran the same commands `dotnet build --configuration Release --no-restore` and `dotnet test --configuration Release --no-build --verbosity normal`. The latter completed, but skipped all tests. :shrug:

Enjoy your weekend. I probably won't be back to my module until Tuesday.

**Comment by jscarle** [comment]
Because tests are run against a real account, they will only run if enabled via the environment variables declared in [TestBase.cs](https://github.com/jscarle/OnePassword.NET/blob/master/OnePassword.NET.Tests/Common/TestsBase.cs).

**Review by jscarle — APPROVED** [review]
I refactored the implementation that was proposed while keeping the same general approach. I also added documentation on how to run the integration tests, while also fixing the actions responsible for testing.

**Pull request merged**
